### ISSUE TITLE
Не обновляется кэш описания информационных баз, если нет соединения с СУБД

### ISSUE THREAD

**Issue by salexdv** [arkuznetsov/hirac#11]
**Описание проблемы**

Использую hirac на машине, где вообще не установлена какая-либо СУБД. RAS запущен на этой же машине, но смотрит он на кластер, расположенный на другом сервере.

racsettings.json по умолчанию.

Обработка запроса списка сессий происходит довольно долго, около 15 секунд. В ответе на запрос нет нормального представления информационной базы

![hirac_none](https://user-images.githubusercontent.com/6356534/175257072-cab0486b-83cc-4d44-8c23-752f68561197.png)

**Причина**

Директива **Продолжить** вот в [этом](https://github.com/arkuznetsov/hirac/blob/eb383795b650c3ef327ddf026d3acaea2428db11/src/model/classes/%D0%9F%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5%D0%9A%D0%90%D0%B3%D0%B5%D0%BD%D1%82%D0%B0%D0%BC.os#L671) месте приводит к тому, что переменная **ОписанияОбъектовКластеров** не заполняется. В момент обновления кэша информационных баз данная переменная является ссылкой на глобальную переменную модуля **ОписанияИнформационныхБаз**, соответственно кэш всегда остается пустым и для каждой сессии заново запрашивается информация по всем базам, и не заполняется поле сессии **label**

Надеюсь понятно описал ))

**Comment by arkuznetsov** [comment]
Хм. я потестю конечно, но на самом деле в этом месте проверяется что нет настроек по ИБ в файле настроек и такая база игнорируется (ключ настроек кластера selectedInfobasesOnly).

**Comment by salexdv** [comment]
Я просто взял последние исходники и запустил, ничего при этом не меняя в racsettings.json. На более ранних версиях (пару месяцев назад) запрос */session/list* возвращал нормальные имена информационных баз, к которой принадлежит сессия, а тут **_none**.
Прошелся отладчиком и увидел, что по стеку *ПолныеОписанияОбъектовКластера -> РасширитьПолеОбъектаКластера -> ПолучитьОписаниеОбъектаИзКэша* переменная **КэшОбъектов** остается пустым соответствием даже после вызова *ОбновитьКэшОписанийОбъектовКластеров*

**Comment by arkuznetsov** [comment]
Попробуй последний develop. И обрати внимание на доку, там добавлен параметр SelectedInfobasesOnly. Т.е. сейчас не должны попадать базы, сеансы и соединения если в настройках не прописано имя базы и `"SelectedInfobasesOnly" : true`.

**Comment by salexdv** [comment]
> Попробуй последний develop. И обрати внимание на доку, там добавлен параметр SelectedInfobasesOnly. Т.е. сейчас не должны попадать базы, сеансы и соединения если в настройках не прописано имя базы и `"SelectedInfobasesOnly" : true`.

Спасибо, попробую. Не нахожу `SelectedInfobasesOnly`  в `racsettings.json` его надо руками добавить?

**Comment by arkuznetsov** [comment]
Да SelectedInfobasesOnly можно добавить руками в дефолтные настройки кластера или в конкретный кластер (в readme сейчас есть), но по умолчанию должны все базы цепляться и, соответственно, все сеансы и соединения. Если не так, то пиши, буду разбираться.

**Comment by salexdv** [comment]
Добавил руками, вот кусок настроек.

```json
{
    "cluster" : {
        "__default" : {
            "admin_name" : "",
            "admin_pwd"  : "",
            "selectedInfobasesOnly" : false,
        },
        "localhost:1541" : {
            "admin_name" : "",
            "admin_pwd"  : "",
            "selectedInfobasesOnly" : false,
            "infobase" : {
                "__default" : {
                    "admin_name" : "Администратор",
                    "admin_pwd"  : "",
                    "dbms_type" : "MSSQLServer",
                    "dbms_server" : "localhost",
                    "dbms_user" : "monitor",
                    "dbms_pwd" : ""
                }
            }
        }
    }
}
```

Кусок ответ на `/session/list`

```json
{
  "session": "0164187f-29a3-4521-aa4f-d8d8d39610fa",
  "session-id": 238605,
  "infobase": "e68be549-e323-4c3e-8770-1c4761b0fdaf",
  "infobase-label": "_none",  // <- Нет имени базы
  "connection": "00000000-0000-0000-0000-000000000000",
  "process": "00000000-0000-0000-0000-000000000000",
  "process-label": "_none",
  "process-host": "_none",
  "user-name": "ИвановИИ",
  "host": "msklad01",
  "app-id": "1CV8C",
  "locale": "ru_RU",
  "started-at": "2022-06-24T08:52:12",
  "duration": 42381,
  "last-active-at": "2022-06-24T20:37:44",
  "hibernate": "no",
  "passive-session-hibernate-time": 1200,
  "hibernate-session-terminate-time": 86400,
  "blocked-by-dbms": 0,
  "blocked-by-ls": 0,
  "bytes-all": 1116597,
  "bytes-last-5min": 6361,
  "calls-all": 1126,
  "calls-last-5min": 5,
  "dbms-bytes-all": 4452336,
  "dbms-bytes-last-5min": 27466,
  "db-proc-info": 0,
  "db-proc-took": 0,
  "db-proc-took-at": "0001-01-01T00:00:00",
  "duration-all": 19045,
  "duration-all-dbms": 5332,
  "duration-current": 0,
  "duration-current-dbms": 0,
  "duration-last-5min": 125,
  "duration-last-5min-dbms": 78,
  "memory-current": 0,
  "memory-last-5min": 439616,
  "memory-total": 143885548,
  "read-current": 0,
  "read-last-5min": 0,
  "read-total": 17742753,
  "write-current": 0,
  "write-last-5min": 0,
  "write-total": 14558433,
  "duration-current-service": 0,
  "current-service-name": "",
  "duration-last-5min-service": 0,
  "duration-all-service": 560,
  "cpu-time-current": 0,
  "cpu-time-5min-last": 0,
  "cpu-time-total": 9593,
  "data-separation": "''",
  "client-ip": "10.14.7.125",
  "agent": "localhost:1545",
  "_type": "session",
  "cluster": "be46d434-de11-4364-a08e-95932fc13232",
  "cluster-host": "ххххх",
  "cluster-port": 1541,
  "cluster-label": "ххххх:1541",
  "id": "0164187f-29a3-4521-aa4f-d8d8d39610fa",
  "label": "_none:238605", // <- Нет имени базы
  "count": 1
}
```

Если комментирую `Продолжить` [тут](https://github.com/arkuznetsov/hirac/blob/eb383795b650c3ef327ddf026d3acaea2428db11/src/model/classes/%D0%9F%D0%BE%D0%B4%D0%BA%D0%BB%D1%8E%D1%87%D0%B5%D0%BD%D0%B8%D0%B5%D0%9A%D0%90%D0%B3%D0%B5%D0%BD%D1%82%D0%B0%D0%BC.os#L671), тогда поля `infobase-label` и `label` заполняются нормально и сессии получаются быстро. 
Может не туда прописал параметр?

**Comment by arkuznetsov** [comment]
Вроде параметр на песте, чот не получается воспроизвести такую картинку. :-( Буду наблюдать.
