### ISSUE TITLE
Не могу настроить hirac

### ISSUE THREAD

**Issue by justdrunkfox** [arkuznetsov/hirac#13]
Не могу настроить hirac, действую по инструкции, конфиг дефолтный, через rac.exe и irac - работает, опрашивается.
Пробовал на Windows и Linux.
Пробовал разные релизы 1с, в данный момент 8.3.22.1709.
Оскрипт  - 1.8.3.
OneScript.Web  0.9.1.

При попытке обратиться по ссылке http://127.0.0.1:5005/cluster/list заканчивается ошибкой:

`
An unhandled exception occurred while processing the request.
RuntimeException: {Модуль C:\Users\user\Desktop\1c\hirac\src\oscript_modules\fluent\src\internal\Модули\ПроцессорыКоллекцийСлужебный.os / Ошибка в строке: 115 / Неверное значение аргумента}
ЭтоФункция = Интерфейс.ПолучитьКартуИнтерфейса()[0].ЭтоФункция;

ScriptEngine.HostedScript.Library.ValueTable.ValueTable.Get(int index)

    Stack Query Cookies Headers Routing 

    RuntimeException: {Модуль C:\Users\user\Desktop\1c\hirac\src\oscript_modules\fluent\src\internal\Модули\ПроцессорыКоллекцийСлужебный.os / Ошибка в строке: 115 / Неверное значение аргумента} ЭтоФункция = Интерфейс.ПолучитьКартуИнтерфейса()[0].ЭтоФункция;
        ScriptEngine.HostedScript.Library.ValueTable.ValueTable.Get(int index)
        ScriptEngine.HostedScript.Library.ValueTable.ValueTable.GetIndexedValue(IValue index)
        ScriptEngine.Machine.Variable+VariableReference.get_DataType()
        ScriptEngine.Machine.MachineInstance.ResolveProp(int arg)
        ScriptEngine.Machine.MachineInstance.MainCommandLoop()
        ScriptEngine.Machine.MachineInstance.ExecuteCode()
        ScriptEngine.Machine.MachineInstance.ExecuteMethod(IRunnable sdo, int methodIndex, IValue[] arguments)
        ScriptEngine.Machine.Contexts.ScriptDrivenObject.CallAsFunction(int methodNumber, IValue[] arguments, out IValue retValue)
        ScriptEngine.Machine.MachineInstance.ResolveMethodFunc(int arg)
        ScriptEngine.Machine.MachineInstance.MainCommandLoop()
        ScriptEngine.Machine.MachineInstance.ExecuteCode()
        ScriptEngine.Machine.MachineInstance.ExecuteMethod(IRunnable sdo, int methodIndex, IValue[] arguments)
        ScriptEngine.Machine.Contexts.ScriptDrivenObject.CallScriptMethod(int methodIndex, IValue[] parameters)
        ScriptEngine.Machine.Contexts.UserScriptContextInstance.OnInstanceCreation()
        ScriptEngine.Machine.Contexts.AttachedScriptsFactory.ScriptFactory(string typeName, IValue[] arguments)
        ScriptEngine.Machine.MachineInstance.NewInstance(int argCount)
        ScriptEngine.Machine.MachineInstance.MainCommandLoop()
        ScriptEngine.Machine.MachineInstance.ExecuteCode()
        ScriptEngine.Machine.MachineInstance.ExecuteMethod(IRunnable sdo, int methodIndex, IValue[] arguments)
        ScriptEngine.Machine.Contexts.ScriptDrivenObject.CallAsFunction(int methodNumber, IValue[] arguments, out IValue retValue)
        ScriptEngine.Machine.MachineInstance.ResolveMethodFunc(int arg)
        ScriptEngine.Machine.MachineInstance.MainCommandLoop()
        ScriptEngine.Machine.MachineInstance.ExecuteCode()
        ScriptEngine.Machine.MachineInstance.ExecuteMethod(IRunnable sdo, int methodIndex, IValue[] arguments)
        ScriptEngine.Machine.Contexts.ScriptDrivenObject.CallAsFunction(int methodNumber, IValue[] arguments, out IValue retValue)
        ScriptEngine.Machine.MachineInstance.ResolveMethodFunc(int arg)
        ScriptEngine.Machine.MachineInstance.MainCommandLoop()
        ScriptEngine.Machine.MachineInstance.ExecuteCode()
        ScriptEngine.Machine.MachineInstance.ExecuteMethod(IRunnable sdo, int methodIndex, IValue[] arguments)
        ScriptEngine.Machine.Contexts.ScriptDrivenObject.CallScriptMethod(int methodIndex, IValue[] parameters)
        ScriptEngine.Machine.Contexts.UserScriptContextInstance.OnInstanceCreation()
        ScriptEngine.Machine.Contexts.AttachedScriptsFactory.ScriptFactory(string typeName, IValue[] arguments)
        ScriptEngine.Machine.MachineInstance.NewInstance(int argCount)
        ScriptEngine.Machine.MachineInstance.MainCommandLoop()
        ScriptEngine.Machine.MachineInstance.ExecuteCode()
        ScriptEngine.Machine.MachineInstance.ExecuteMethod(IRunnable sdo, int methodIndex, IValue[] arguments)
        ScriptEngine.Machine.Contexts.ScriptDrivenObject.CallScriptMethod(int methodIndex, IValue[] parameters)
        ScriptEngine.Machine.Contexts.UserScriptContextInstance.OnInstanceCreation()
        ScriptEngine.Machine.Contexts.AttachedScriptsFactory.ScriptFactory(string typeName, IValue[] arguments)
        ScriptEngine.Machine.MachineInstance.NewInstance(int argCount)
        ScriptEngine.Machine.MachineInstance.MainCommandLoop()
        ScriptEngine.Machine.MachineInstance.ExecuteCode()
        ScriptEngine.Machine.MachineInstance.ExecuteMethod(IRunnable sdo, int methodIndex, IValue[] arguments)
        ScriptEngine.Machine.Contexts.ScriptDrivenObject.CallScriptMethod(int methodIndex, IValue[] parameters)
        ScriptEngine.Machine.Contexts.UserScriptContextInstance.OnInstanceCreation()
        ScriptEngine.Machine.Contexts.AttachedScriptsFactory.ScriptFactory(string typeName, IValue[] arguments)
        ScriptEngine.Machine.MachineInstance.NewInstance(int argCount)
        ScriptEngine.Machine.MachineInstance.MainCommandLoop()
        ScriptEngine.Machine.MachineInstance.ExecuteCode()
        ScriptEngine.Machine.MachineInstance.ExecuteMethod(IRunnable sdo, int methodIndex, IValue[] arguments)
        ScriptEngine.Machine.Contexts.ScriptDrivenObject.CallAsFunction(int methodNumber, IValue[] arguments, out IValue retValue)
        ScriptEngine.Machine.MachineInstance.ResolveMethodFunc(int arg)
        ScriptEngine.Machine.MachineInstance.MainCommandLoop()
        ScriptEngine.Machine.MachineInstance.ExecuteCode()
        ScriptEngine.Machine.MachineInstance.ExecuteMethod(IRunnable sdo, int methodIndex, IValue[] arguments)
        ScriptEngine.Machine.Contexts.ScriptDrivenObject.CallAsFunction(int methodNumber, IValue[] arguments, out IValue retValue)
        ScriptEngine.Machine.Contexts.ReflectedMethodInfo.InvokeDirect(IRuntimeContextInstance instance, IValue[] parameters)
        OneScript.WebHost.Application.ScriptedController.ResultAction() in ScriptedController.cs
        lambda_method(Closure , object , object[] )
        Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(object target, object[] parameters)
        Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor+SyncActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, object controller, object[] arguments)
        Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
        Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
        Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
        Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
        Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
        Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, object state, bool isCompleted)
        Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
        Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
        Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
        Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
        Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
        Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

`

ЧЯДНТ?

**Comment by arkuznetsov** [comment]
Для начала попробуйте поставить последний OneScript.Web https://github.com/EvilBeaver/OneScript.Web/releases/tag/v0.9.3 и проверить/обновить версию библиотеки fluent.

**Comment by justdrunkfox** [comment]
Благодарю за подсказку, заработало с fluent версии 0.5, с 0.6 не работает.
Без 0.5 как обычно не разобраться.)

**Comment by justdrunkfox** [comment]
Похоже рано я обрадовался.
После замены fluent, я для проверки несколько раз успешно спросил - http://127.0.0.1:5005/cluster/list, ответ был как у rac'a. Я немного "поэкспериментировал" и по /cluster/list начал приходить пустой ответ - []. Я все снес и установил заново, включая 1с, чистые конфиги и fluent 0.5.
В результате irac и rac опрашиваются нормально, а через hirac ответ - [].

В логе:
dbug: Microsoft.AspNetCore.Hosting.Diagnostics[3]
      Hosting starting
dbug: OneScript.WebHost.Application.ApplicationInstance[0]
      No database configured
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\user\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
dbug: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[37]
      Reading data from file 'C:\Users\user\AppData\Local\ASP.NET\DataProtection-Keys\key-cba6df75-39b3-429f-8c0e-307b1123eee9.xml'.
dbug: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[18]
      Found key {cba6df75-39b3-429f-8c0e-307b1123eee9}.
dbug: Microsoft.AspNetCore.DataProtection.KeyManagement.DefaultKeyResolver[13]
      Considering key {cba6df75-39b3-429f-8c0e-307b1123eee9} with expiration date 2023-09-04 07:04:14Z as default key.
dbug: Microsoft.AspNetCore.DataProtection.TypeForwardingActivator[0]
      Forwarded activator type request from Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor, Microsoft.AspNetCore.DataProtection, Version=3.1.12.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 to Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor, Microsoft.AspNetCore.DataProtection, Culture=neutral, PublicKeyToken=adb9793829ddae60
dbug: Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor[51]
      Decrypting secret element using Windows DPAPI.
dbug: Microsoft.AspNetCore.DataProtection.TypeForwardingActivator[0]
      Forwarded activator type request from Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=3.1.12.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 to Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Culture=neutral, PublicKeyToken=adb9793829ddae60
dbug: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.CngCbcAuthenticatedEncryptorFactory[4]
      Opening CNG algorithm 'AES' from provider '(null)' with chaining mode CBC.
dbug: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.CngCbcAuthenticatedEncryptorFactory[3]
      Opening CNG algorithm 'SHA256' from provider '(null)' with HMAC.
dbug: Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider[2]
      Using key {cba6df75-39b3-429f-8c0e-307b1123eee9} as the default key.
dbug: Microsoft.AspNetCore.DataProtection.Internal.DataProtectionHostedService[0]
      Key ring with default key {cba6df75-39b3-429f-8c0e-307b1123eee9} was loaded during application startup.
Hosting environment: Development
Content root path: C:\hirac\app
dbugNow listening on: http://localhost:5005
Application started. Press Ctrl+C to shut down.
: Microsoft.AspNetCore.Hosting.Diagnostics[4]
      Hosting started
dbug: Microsoft.AspNetCore.Hosting.Diagnostics[0]
      Loaded hosting startup assembly OneScript.WebHost
dbug: Microsoft.AspNetCore.Server.Kestrel[39]
      Connection id "0HMRRIAJFGKMJ" accepted.
dbug: Microsoft.AspNetCore.Server.Kestrel[1]
      Connection id "0HMRRIAJFGKMJ" started.
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://127.0.0.1:5005/cluster/list
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1001]
      2 candidate(s) found for the request path '/cluster/list'
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]
      Endpoint 'OneScript.WebHost.Application.ScriptedController.ResultAction (OneScript.WebHost)' with route pattern 'cluster/list' is valid for the request path '/cluster/list'
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]
      Endpoint 'OneScript.WebHost.Application.ScriptedController.ResultAction (OneScript.WebHost)' with route pattern 'cluster/{id}/{property?}' is valid for the request path '/cluster/list'
dbug: Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware[1]
      Request matched endpoint 'OneScript.WebHost.Application.ScriptedController.ResultAction (OneScript.WebHost)'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'OneScript.WebHost.Application.ScriptedController.ResultAction (OneScript.WebHost)'
dbug: Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory[12]
      Registered model binder providers, in the following order: Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BinderTypeModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ServicesModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.HeaderModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FloatingPointTypeModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.EnumTypeModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.SimpleTypeModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CancellationTokenModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ByteArrayModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FormFileModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FormCollectionModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.KeyValuePairModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.DictionaryModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ArrayModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CollectionModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexTypeModelBinderProvider
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "list", controller = "clusterObject"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult ResultAction() on controller OneScript.WebHost.Application.ScriptedController (OneScript.WebHost).
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Execution plan of authorization filters (in the following order): None
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000)
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Execution plan of exception filters (in the following order): None
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Executing controller factory for controller OneScript.WebHost.Application.ScriptedController (OneScript.WebHost)
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed controller factory for controller OneScript.WebHost.Application.ScriptedController (OneScript.WebHost)
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Executing action method OneScript.WebHost.Application.ScriptedController.ResultAction (OneScript.WebHost) - Validation state: Valid
fail: OneScript.WebHost.Application.ApplicationInstance[0]
      Занимаем подключение: 0
fail: OneScript.WebHost.Application.ApplicationInstance[0]
      При проверке доступности агента
не удалось получить список кластеров у сервиса администрирования "localhost:1545"
fail: OneScript.WebHost.Application.ApplicationInstance[0]
      Освободили подключение: 0
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action method OneScript.WebHost.Application.ScriptedController.ResultAction (OneScript.WebHost), returned result Microsoft.AspNetCore.Mvc.ContentResult in 273.0157ms.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ContentResultExecutor[1]
      Executing ContentResult with HTTP Response ContentType of text/plain; charset=utf-8
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action OneScript.WebHost.Application.ScriptedController.ResultAction (OneScript.WebHost) in 284.0294ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'OneScript.WebHost.Application.ScriptedController.ResultAction (OneScript.WebHost)'
dbug: Microsoft.AspNetCore.Server.Kestrel[9]
      Connection id "0HMRRIAJFGKMJ" completed keep alive response.
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 322.6731ms 200 text/plain; charset=utf-8

**Comment by arkuznetsov** [comment]
Попробуй взять вот эту https://github.com/arkuznetsov/OneScript.Web/releases/download/v0.9.5/oscript.web-win-x64.zip сборку.

**Comment by justdrunkfox** [comment]
Эта сборка попросила ASP.NET (v3.1.32) и не падает с fluent 0.6.0, но результат опять - []

dbug: Microsoft.AspNetCore.Hosting.Diagnostics[3]
      Hosting starting
dbug: OneScript.WebHost.Application.ApplicationInstance[0]
      No database configured
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using 'C:\Users\user\AppData\Local\ASP.NET\DataProtection-Keys' as key repository and Windows DPAPI to encrypt keys at rest.
dbug: Microsoft.AspNetCore.DataProtection.Repositories.FileSystemXmlRepository[37]
      Reading data from file 'C:\Users\user\AppData\Local\ASP.NET\DataProtection-Keys\key-cba6df75-39b3-429f-8c0e-307b1123eee9.xml'.
dbug: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[18]
      Found key {cba6df75-39b3-429f-8c0e-307b1123eee9}.
dbug: Microsoft.AspNetCore.DataProtection.KeyManagement.DefaultKeyResolver[13]
      Considering key {cba6df75-39b3-429f-8c0e-307b1123eee9} with expiration date 2023-09-04 07:04:14Z as default key.
dbug: Microsoft.AspNetCore.DataProtection.TypeForwardingActivator[0]
      Forwarded activator type request from Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor, Microsoft.AspNetCore.DataProtection, Version=3.1.12.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 to Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor, Microsoft.AspNetCore.DataProtection, Culture=neutral, PublicKeyToken=adb9793829ddae60
dbug: Microsoft.AspNetCore.DataProtection.XmlEncryption.DpapiXmlDecryptor[51]
      Decrypting secret element using Windows DPAPI.
dbug: Microsoft.AspNetCore.DataProtection.TypeForwardingActivator[0]
      Forwarded activator type request from Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Version=3.1.12.0, Culture=neutral, PublicKeyToken=adb9793829ddae60 to Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.ConfigurationModel.AuthenticatedEncryptorDescriptorDeserializer, Microsoft.AspNetCore.DataProtection, Culture=neutral, PublicKeyToken=adb9793829ddae60
dbug: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.CngCbcAuthenticatedEncryptorFactory[4]
      Opening CNG algorithm 'AES' from provider '(null)' with chaining mode CBC.
dbug: Microsoft.AspNetCore.DataProtection.AuthenticatedEncryption.CngCbcAuthenticatedEncryptorFactory[3]
      Opening CNG algorithm 'SHA256' from provider '(null)' with HMAC.
dbug: Microsoft.AspNetCore.DataProtection.KeyManagement.KeyRingProvider[2]
      Using key {cba6df75-39b3-429f-8c0e-307b1123eee9} as the default key.
dbug: Microsoft.AspNetCore.DataProtection.Internal.DataProtectionHostedService[0]
      Key ring with default key {cba6df75-39b3-429f-8c0e-307b1123eee9} was loaded during application startup.
Hosting environment: Development
Content root path: C:\hirac\app
dbugNow listening on: http://localhost:5005
Application started. Press Ctrl+C to shut down.
: Microsoft.AspNetCore.Hosting.Diagnostics[4]
      Hosting started
dbug: Microsoft.AspNetCore.Hosting.Diagnostics[0]
      Loaded hosting startup assembly OneScript.WebHost
dbug: Microsoft.AspNetCore.Server.Kestrel[39]
      Connection id "0HMRRKCT0NS9N" accepted.
dbug: Microsoft.AspNetCore.Server.Kestrel[1]
      Connection id "0HMRRKCT0NS9N" started.
info: Microsoft.AspNetCore.Hosting.Diagnostics[1]
      Request starting HTTP/1.1 GET http://127.0.0.1:5005/cluster/list
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1001]
      2 candidate(s) found for the request path '/cluster/list'
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]
      Endpoint 'OneScript.WebHost.Application.ScriptedController.ResultAction (OneScript.WebHost)' with route pattern 'cluster/list' is valid for the request path '/cluster/list'
dbug: Microsoft.AspNetCore.Routing.Matching.DfaMatcher[1005]
      Endpoint 'OneScript.WebHost.Application.ScriptedController.ResultAction (OneScript.WebHost)' with route pattern 'cluster/{id}/{property?}' is valid for the request path '/cluster/list'
dbug: Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware[1]
      Request matched endpoint 'OneScript.WebHost.Application.ScriptedController.ResultAction (OneScript.WebHost)'
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[0]
      Executing endpoint 'OneScript.WebHost.Application.ScriptedController.ResultAction (OneScript.WebHost)'
dbug: Microsoft.AspNetCore.Mvc.ModelBinding.ModelBinderFactory[12]
      Registered model binder providers, in the following order: Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BinderTypeModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ServicesModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.BodyModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.HeaderModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FloatingPointTypeModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.EnumTypeModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.SimpleTypeModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CancellationTokenModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ByteArrayModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FormFileModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.FormCollectionModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.KeyValuePairModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.DictionaryModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ArrayModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.CollectionModelBinderProvider, Microsoft.AspNetCore.Mvc.ModelBinding.Binders.ComplexTypeModelBinderProvider
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[3]
      Route matched with {action = "list", controller = "clusterObject"}. Executing controller action with signature Microsoft.AspNetCore.Mvc.IActionResult ResultAction() on controller OneScript.WebHost.Application.ScriptedController (OneScript.WebHost).
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Execution plan of authorization filters (in the following order): None
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Execution plan of resource filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Execution plan of action filters (in the following order): Microsoft.AspNetCore.Mvc.ModelBinding.UnsupportedContentTypeFilter (Order: -3000)
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Execution plan of exception filters (in the following order): None
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Execution plan of result filters (in the following order): Microsoft.AspNetCore.Mvc.ViewFeatures.Filters.SaveTempDataFilter
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Executing controller factory for controller OneScript.WebHost.Application.ScriptedController (OneScript.WebHost)
dbug: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed controller factory for controller OneScript.WebHost.Application.ScriptedController (OneScript.WebHost)
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[1]
      Executing action method OneScript.WebHost.Application.ScriptedController.ResultAction (OneScript.WebHost) - Validation state: Valid
warn: OneScript.WebHost.Application.ApplicationInstance[0]
      ПРЕДУПРЕЖДЕНИЕ -
 Использование синтаксиса лямбда выражений без "->" а так же описания оповещения является устаревшим
 и будет удален в последующих версиях, необходимо заменить места использования
warn: OneScript.WebHost.Application.ApplicationInstance[0]
      ПРЕДУПРЕЖДЕНИЕ -
 Использование синтаксиса лямбда выражений без "->" а так же описания оповещения является устаревшим
 и будет удален в последующих версиях, необходимо заменить места использования
warn: OneScript.WebHost.Application.ApplicationInstance[0]
      ПРЕДУПРЕЖДЕНИЕ -
 Использование синтаксиса лямбда выражений без "->" а так же описания оповещения является устаревшим
 и будет удален в последующих версиях, необходимо заменить места использования
fail: OneScript.WebHost.Application.ApplicationInstance[0]
      Занимаем подключение: 0
fail: OneScript.WebHost.Application.ApplicationInstance[0]
      При проверке доступности агента
не удалось получить список кластеров у сервиса администрирования "localhost:1545"
fail: OneScript.WebHost.Application.ApplicationInstance[0]
      Освободили подключение: 0
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action method OneScript.WebHost.Application.ScriptedController.ResultAction (OneScript.WebHost), returned result Microsoft.AspNetCore.Mvc.ContentResult in 440.3996ms.
info: Microsoft.AspNetCore.Mvc.Infrastructure.ContentResultExecutor[1]
      Executing ContentResult with HTTP Response ContentType of text/plain; charset=utf-8
info: Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker[2]
      Executed action OneScript.WebHost.Application.ScriptedController.ResultAction (OneScript.WebHost) in 453.0767ms
info: Microsoft.AspNetCore.Routing.EndpointMiddleware[1]
      Executed endpoint 'OneScript.WebHost.Application.ScriptedController.ResultAction (OneScript.WebHost)'
dbug: Microsoft.AspNetCore.Server.Kestrel[9]
      Connection id "0HMRRKCT0NS9N" completed keep alive response.
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
      Request finished in 498.4177ms 200 text/plain; charset=utf-8

**Comment by justdrunkfox** [comment]
Попробовал поставить iracli, он работает.

**Comment by arkuznetsov** [comment]
Значит надо в отладчик лезть, смотреть, что происходит.

**Comment by justdrunkfox** [comment]
Понял, а чем можно поотлаживать?

**Comment by arkuznetsov** [comment]
В Visual Studio Code установить отладчик "OneScript Debug (BSL)"

**Comment by justdrunkfox** [comment]
Еще вопрос.
Поставил Visual Studio и OneScript Debug (BSL).
Добавил в Visual Studio папку с hirac, ту где лежит main.os.
Нажимаю F5, выбираю "1Script Debugger for 1Script.web" и ничего. Пробовал так же выбирать "Debugger for 1Script" тот что без web.
Я так понял что должен создаться файл launch.json?

Что делать и куда дальше копать?
Это мой первый опыт в этом вопросе, может где-то есть инструкция по настройке?
