### ISSUE TITLE
Не отображается русский язык

### ISSUE THREAD

**Issue by howard180** [arkuznetsov/hirac#5]
Проблема с отображением русского языка. 
Режим запуска: в контейнере, на Ubuntu.

Пример ответа в браузере:
`                "name": "╨Ы╨╛╨║╨░╨╗╤М╨╜╤Л╨╣ ╨║╨╗╨░╤Б╤В╨╡╤А",
		"lifetime-limit": 0,
		"max-memory-size": 0,
		"security-level": 0,
		"session-fault-tolerance-level": 0,`

**Comment by arkuznetsov** [comment]
Спасибо! Посмотрю на днях.

**Comment by howard180** [comment]
Решил дать побольше информации: 

- RAS и сервер 1С запущен на Windows.
- А вот hirac  в контейнере.

**Comment by howard180** [comment]
Еще в дополнение: проводил эксперимент, когда:

- Сервер предприятия на windows
- ras в контейнере на linux
- hirac в контейнере на linux

При такой комбинации ошибка с некорректным отображением русского языка также воспроизводится.

**Comment by howard180** [comment]
- В рантайме в лог hirac выводили JSON, который потом возвращается браузеру, русский язык некорректно отображался.
- Так же в добавили код, который в лог выводит простой русский текст - в лог вывелся нормальный русский текст. 
- Есть подозрение, что irac возвращает hirac некорректный русский язык.

**Comment by howard180** [comment]
Вот, что обнаружил в irac: "Команда.УстановитьКодировкуВывода(КодировкаТекста.OEM);"
Кажется, это - источник проблемы.

**Comment by arkuznetsov** [comment]
Попробуй поменять на КодировкаТекста.UTF8. Но скорее всего проблема в том что RAC возвращает такие поля в OEM кодировке. Возвможно надо будет добавить преобразование.

**Comment by howard180** [comment]
Попробовал. Поменял на "КодировкаТекста.UTF8" и все заработало: русский язык отображается нормально.
Как сделал: добавил новый слой при сборке финального Docker-образа, который меняет строку в файле библиотеки irac.

**Comment by howard180** [comment]
Подскажите, пожалуйста, планируется ли в IRAC исправление то, о котором я писал выше?

**Comment by arkuznetsov** [comment]
Посмотрю, что можно сделать на этой неделе.

**Comment by arkuznetsov** [comment]
Попробуй взять irac из develop.

**Comment by howard180** [comment]
В dicker-образе, который я собираю вашим скриптом, уже имеется библиотека irac.
Как мне поправить скрипт, чтобы туда попал irac из нужно ветки?

**Comment by arkuznetsov** [comment]
Уже зарелизился irac с исправлениями, если пересобрать образ, то подтянется свежий.

**Comment by arkuznetsov** [comment]
@howard180 получилось?
